feat: Google Map API connection
Beginneraboutlife116/isport pull request #32
Opened 2023-07-19 11:17 UTC by Ollieeryo

建立 Google Map 元件，串接 google map API 到 card component。

2023-07-19 16:38 UTC, Beginneraboutlife116 requested changes
我這邊有遇到一個無限的 render 問題，你有遇到嗎？

以下是 GIF 圖
![inifite-render](https://github.com/Beginneraboutlife116/isport/assets/78048447/c4c0ddb7-9938-40f4-abb0-6879cc855c3c)

2023-07-19 16:38 UTC, Beginneraboutlife116 commented on tsconfig.json
> +    "types": ["googlemaps"],
![截圖 2023-07-20 上午12 32 50](https://github.com/Beginneraboutlife116/isport/assets/78048447/aae076e5-2825-4565-8a11-b35e070616a9)

我有遇到這個錯誤資訊，你那邊會嗎？

2023-07-19 17:06 UTC, Ollieeryo commented on tsconfig.json
> +    "types": ["googlemaps"],
無限迴圈的問題: 我測試了一下，應該是 state 的關係，我剛剛重新設計成 ref 後測試後沒問題，在新的 push 中你可以再開地圖看看。

tsconfig: 我這邊沒有顯示錯誤，不過這個設定應該不用放也沒關係，所以剛剛新的 push 我也先把 types: googlemaps 拿掉。

2023-07-20 04:10 UTC, Beginneraboutlife116 commented on tsconfig.json
> +    "types": ["googlemaps"],
沒有再看到無限迴圈的問題了，但出現這個問題，我覺得是沒有偵測到 api key

<img width="1440" alt="截圖 2023-07-20 下午12 09 55" src="https://github.com/Beginneraboutlife116/isport/assets/78048447/c8767966-450a-4918-a5e9-057e6a5dcf3f">

2023-07-20 04:14 UTC, Ollieeryo commented on tsconfig.json
> +    "types": ["googlemaps"],
對，忘了說這點，因為 env 檔案(環境變數)預設是不上傳到 github (裡面有API key)，API key 要在部屬完網站再去環境變數設定。

2023-07-20 05:01 UTC, Beginneraboutlife116 commented on tsconfig.json
> +    "types": ["googlemaps"],
那我先手動新增應該可以對吧？

2023-07-20 05:06 UTC, Ollieeryo commented on tsconfig.json
> +    "types": ["googlemaps"],
可以的

2023-07-20 06:18 UTC, Beginneraboutlife116 approved these changes

2023-07-20 06:18 UTC, merged